version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source.
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of sales
          - name: orders_id
            description: primary key of sales
          - name: products_id
            description: the forign key of sales
          - name: revenue
            description: the revenue of sales
          - name: quantity
            description: the quantity of sales
      
      - name: product
        identifier: raw_gz_product
        description: product of greenweez
        columns:
          - name: products_id
            description: the primary key of products
            tests: 
            - not_null
            - unique  
          - name: purchase_price
            description: the purchase price of product

      - name: ship
        identifier: raw_gz-ship
        description: ship of greenweez

        columns:
          - name: orders_id
            description: the forign key  of ship
            tests:
               - not_null
               - unique 
          - name: orders_shipping
            tests:
               - not_null
               - unique 
          - name: shipping_fee
            description: the shipping fee of ship
          - name: logcost
            description: the logcost of ship
          - name: ship_cost
            description: the ship cost of ship